# Generated by Django 4.0.1 on 2022-01-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Employee', max_length=25),
        ),
    ]
