# Generated by Django 4.0.1 on 2022-01-11 05:37

from django.db import migrations, models
import employee.models
import employee.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadhar_card',
            field=models.FileField(upload_to=employee.models.Employee.aadharFile, validators=[employee.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='driving_license',
            field=models.FileField(upload_to=employee.models.Employee.licenseFile, validators=[employee.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_card',
            field=models.FileField(upload_to=employee.models.Employee.panFile, validators=[employee.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport',
            field=models.FileField(upload_to=employee.models.Employee.passportFile, validators=[employee.validators.validate_file_extension]),
        ),
    ]
