# Generated by Django 4.0.1 on 2022-01-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_age_alter_employee_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
