# Generated by Django 4.0.1 on 2022-01-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_invite_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
